config/routes.rb
Rails.application.routes.draw do
  resources :trip_files
  resources :records
  
  root to: 'records#new'
  
  get 'table' => 'records#table'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/record.rb
class Record < ApplicationRecord
	mount_uploader :doc, FileUploader
	# after_create :set_filename


	# def set_filename
	#     if self.file.attached?
	#       self.file.blob.update(filename: "#{self.awbnum}.#{self.file.filename.extension}")
	#     end
 #  	end
end

app/models/trip_file.rb
class TripFile < ApplicationRecord
	mount_uploader :doc, DocUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  require 'open-uri'
  require 'zip/zip'
  require 'rubygems'
  require 'zip'

  before_action :set_record, only: [:show, :edit, :update, :destroy]
  before_action :set_timezone

  # GET /records
  # GET /records.json
  def table
    @records = Record.all
    # @files = Record.all
    
    # render json: @records.map { |record|
    #     record.as_json.merge({ file: url_for(record.file) })
    # }

  end

  # GET /records/1
  # GET /records/1.json
  def show
    # redirect_to @record.file.service_url(filename: filename)
  end

  # GET /records/new
  def new
    @record = Record.new
  end

  # GET /records/1/edit
  def edit
  end

  # POST /records
  # POST /records.json
  def create
    @record = Record.new(record_params)

    respond_to do |format|
      if @record.save
        format.html { redirect_to @record, notice: 'Record was successfully created.' }
        format.json { render :show, status: :created, location: @record }
      else
        format.html { render :new }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /records/1
  # PATCH/PUT /records/1.json
  def update
    respond_to do |format|
      if @record.update(record_params)
        format.html { redirect_to @record, notice: 'Record was successfully updated.' }
        format.json { render :show, status: :ok, location: @record }
      else
        format.html { render :edit }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1
  # DELETE /records/1.json
  def destroy
    @record.destroy
    respond_to do |format|
      format.html { redirect_to table_path, notice: 'Record was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def batch_download
    if params["record"].present?
      ids = params["record"].to_unsafe_h.map(&:first)

      if ids.present?
        # folder = []
        # input_filenames = []
        # Record.where(id: ids).each do |attachment| 
        #   input_filenames.push("#{attachment.file.filename}")
        #   pre_path = "/rails/active_storage/blobs/"
        #   path_find = "#{rails_blob_path(attachment.file)}"
        #   folder.push(pre_path + path_find.split('/')[4])
        # end
        # container = Hash[folder.zip(input_filenames)]

        # zipfile_name = "/Users/fahimabdullah/Documents/archive.zip"

        # Zip::File.open(zipfile_name, Zip::File::CREATE) do |zipfile|
        #   # input_filenames.each do |filename|
        #   container.map do |path, filename|
        #   zipfile.add(filename, File.join(path, filename))
        #   end
        #   zipfile.get_output_stream("myFile") { |f| f.write "myFile contains just this" }
        # end
        # =====
    #     folder_path = "#{Rails.root}/public/downloads/"
    #     zipfile_name = "#{Rails.root}/public/archive.zip"

    #     FileUtils.remove_dir(folder_path) if Dir.exist?(folder_path)
    #     FileUtils.remove_entry(zipfile_name) if File.exist?(zipfile_name)
    #     Dir.mkdir("#{Rails.root}/public/downloads")

    #     Record.where(id: ids).each do |attachment|
    #       open(folder_path + "#{attachment.file.filename}", 'wb') do |file|
    #         # file << "#{(attachment.file)}"
    #         file << open("#{attachment.doc.url}").read
    #         # file << open("#{rails_blob_path(attachment.file)}").read
    #       end
    #     end

    #     input_filenames = Dir.entries(folder_path).select {|f| !File.directory? f}

    #     Zip::File.open(zipfile_name, Zip::File::CREATE) do |zipfile|
    #       input_filenames.each do |attachment|
    #         zipfile.add(attachment,File.join(folder_path,attachment))
    #       end
    #     end

    #     send_file(File.join("#{Rails.root}/public/", 'archive.zip'), :type => 'application/zip', :filename => "#{Time.now.to_date}.zip")
    #   end
    # else
    #   redirect_back fallback_location: root_path
    end
  end
end

private
    # Use callbacks to share common setup or constraints between actions.
    def set_record
      @record = Record.find(params[:id])
    end

    def set_timezone
      Time.zone = "Kuala Lumpur"
    end

    # def set_start_end_times
    #   @start_time = params[:start_time].present? ? Time.zone.parse(params[:start_time]) : Time.now - 14.day
    #   @end_time   = params[:end_time].present? ? Time.zone.parse(params[:end_time]).end_of_day : Time.now
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    def record_params
      params.require(:record).permit(:prefix, :awbnum, :doc)
    end
end

app/controllers/trip_files_controller.rb
class TripFilesController < ApplicationController
  before_action :set_trip_file, only: [:show, :edit, :update, :destroy]

  # GET /trip_files
  # GET /trip_files.json
  def index
    @trip_files = TripFile.all
  end

  # GET /trip_files/1
  # GET /trip_files/1.json
  def show
  end

  # GET /trip_files/new
  def new
    @trip_file = TripFile.new
  end

  # GET /trip_files/1/edit
  def edit
  end

  # POST /trip_files
  # POST /trip_files.json
  def create
    @trip_file = TripFile.new(trip_file_params)

    respond_to do |format|
      if @trip_file.save
        format.html { redirect_to @trip_file, notice: 'Trip file was successfully created.' }
        format.json { render :show, status: :created, location: @trip_file }
      else
        format.html { render :new }
        format.json { render json: @trip_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trip_files/1
  # PATCH/PUT /trip_files/1.json
  def update
    respond_to do |format|
      if @trip_file.update(trip_file_params)
        format.html { redirect_to @trip_file, notice: 'Trip file was successfully updated.' }
        format.json { render :show, status: :ok, location: @trip_file }
      else
        format.html { render :edit }
        format.json { render json: @trip_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trip_files/1
  # DELETE /trip_files/1.json
  def destroy
    @trip_file.destroy
    respond_to do |format|
      format.html { redirect_to trip_files_url, notice: 'Trip file was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip_file
      @trip_file = TripFile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trip_file_params
      params.require(:trip_file).permit(:flight, :flight_number, :doc, :date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/trip_files_helper.rb
module TripFilesHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-md static-top">
  <div class="container">
      <a class="navbar-brand" href="https://redcargo.asia">
          <img src="https://www.redcargo.asia/wp-content/uploads/2018/07/cargo-asia-logo.png" width="20%" alt="" style="background-color: white;">
      </a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
          <%= image_tag("ham.png", :alt => "menu", :style => "width: 25px") %>
      </button>

      <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                  <%= link_to 'AWB Uploader', new_record_path, class: 'nav-link' %>
              </li>

              <li class="nav-item">
                <%= link_to 'Export Manifest Uploader', new_trip_file_path, class: 'nav-link' %>
              </li>
              <!-- <li class="nav-item">
                  <a class="nav-link" href="#">Admin Login</a>
              </li> -->
          </ul>
      </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AWB Uploader</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%=  stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Cabin|Quicksand' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>

    <%= yield %>

  </body>
</html>

app/views/records/_form.html.erb
<%= form_with(model: record, local: true, class: 'form-horizontal') do |form| %>
  <% if record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(record.errors.count, "error") %> prohibited this record from being saved:</h2>
      <ul>
      <% record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <%= form.number_field :prefix, :required => true, id: "first", class: 'form-control col-2', placeholder: 'Prefix', pattern: "/^-?\d+\.?\d*$/", :onKeyPress => "if(this.value.length==3) return false;", :style => "padding: 10px; margin-right: 10px;" %>
    <%= form.number_field :awbnum, :required => true, id: "second", class: 'form-control col-9', placeholder: 'AWB Number', pattern: "/^-?\d+\.?\d*$/", :onKeyPress => "if(this.value.length==8) return false;", :style => "padding: 10px; margin-right: 10px;" %>
  </div>

  <div class="row">
    <%= form.file_field :doc, :required => true, class: 'uploadBtn col-12', :accept => "image/*", :style => "padding: 10px 0" %>
  </div>
  <div class="row">

    <%= form.submit 'Submit', id: "submit", :class => 'submit' %>
  </div>
<% end %>

app/views/records/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-12">
			<h1 class="red-heading">Editing Record</h1>
		</div>
	</div>

	<div class="row">
		<div class="col-md-6 col-12" style="padding : 0px 0 0 43px">
			<%= render 'form', record: @record %>
			<%= link_to 'Show', @record %> |
			<%= link_to 'Back', records_path %>
		</div>
	</div>
</div>

app/views/records/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-12">
			<br><br>
			<h1 class="red-heading">RedCargo AWB Uploader</h1>
			<p>Key in AWB Number, Snap a picture and Submit!</p>
		</div>
	</div>

	<div class="col-md-6 col-12">
		<%= render 'form', record: @record %>
	</div>
</div>

app/views/records/show.html.erb
<div class="container my-4">

	<% if notice %>
	<div class="alert alert-success alert-dismissible fade show">
		<button type="button" class="close" data-dismiss="alert">&times;</button>
		<p id="notice"><%= notice %></p>
	</div>
	<% end %>

	<div class="jumbotron bg-light py-4">
		<div class="row">
			<figure class="figure">
				<%#= image_tag @record.doc.url, class: "figure-img img-fluid rounded", width: "80%" %>
				<figcaption class="figure-caption" style="font-size: 18px;">AWB Number : <%= @record.awbnum %></figcaption>
			</figure>
		</div>
		<div class="row">
			<%= link_to 'Create New', new_record_path, class: 'awb-button btn btn-success' %>
		</div>
	</div>
</div>

app/views/records/table.html.erb
<div class="container">
  <h1 class="red-heading" style="padding: 0; margin: 30px 0 15px 0;">RECORD TABLE</h1>
  <div class="row">
    <div class="col-12">
      <p id="notice"><%= notice %></p>
      <table id="awbtable" class="table table-hover">
        <thead class="thead-light">
          <tr>
            
            <th>Airway Bill</th>
            <th>Date Created</th>
            <th class="no-sort">Actions</th>
          </tr>
        </thead>

        <tbody>
          <% @records.each do |record| %>
            <tr>
              <td><%= record.prefix + '-' + record.awbnum %></td>
              <td><%= record.created_at.strftime("%d %b %Y - %H:%M") %>
              <td><%= link_to 'Show', record, class: 'btn btn-outline-primary btn-sm' %> 
                  <%#= link_to 'Download', record.doc.url, download: '', class: 'btn btn-outline-success btn-sm' %> 
                  <%= link_to 'Edit', edit_record_path(record), class: 'btn btn-outline-warning btn-sm' %> 
                  <%= link_to 'Delete', record, method: :delete, class: 'btn btn-outline-danger btn-sm' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= link_to 'New Record', new_record_path, class: 'btn btn-success' %>
      <%#= submit_tag "Download", class: 'awb-button btn2' %>
    </div>
  </div>
</div>

app/views/trip_files/_form.html.erb
<%= form_with(model: trip_file, local: true) do |form| %>
  <% if trip_file.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(trip_file.errors.count, "error") %> prohibited this trip_file from being saved:</h2>
      <ul>
      <% trip_file.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row mb-1">
    <%= form.text_field :flight, :required => true, class: 'mr-1 form-control col-md-4 col-3', placeholder: 'Flight', :style => "padding: 10px; margin-right: 10px;" %>
    <%= form.text_field :flight_number, :required => true, class: 'form-control col-md col', placeholder: 'Number' %>
  </div>
  <div class="row mb-1">
    <%= form.text_field :date, :required => true, class: 'form-control col-md mx-0', placeholder: 'DD-MM-YYYY', :style => "padding: 10px; margin-right: 10px;" %>
  </div>
  <div class="row">
    <hr class="col">  
  </div>

  <div class="row mb-2">
    <%= form.file_field :doc, :required => true, class: 'mb-2 px-0 uploadBtn col-12', :accept => "image/*" %>
  </div>

  <div class="row">
    <%= form.submit 'Submit', id: "submit", :class => 'submit' %>
  </div>

<% end %>

app/views/trip_files/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-12">
			<br><br>
			<h1 class="red-heading">Edit Trip File</h1>
		</div>
	</div>

	<div class="col-md-6 col-12">
		<%= render 'form', trip_file: @trip_file %>
	</div>
</div>

app/views/trip_files/index.html.erb
<div class="container">
    <h1 class="red-heading" style="padding: 0; margin: 30px 0 15px 0;">TRIP FILES TABLE</h1>
    <div class="row">
      <div class="col-12">
        <p id="notice"><%= notice %></p>
        <table id="tf-table" class="table table-hover">
          <thead class="thead-light">
            <tr>
              <th>Flight</th>
              <th>Date Created</th>
              <th class="no-sort">Actions</th>
            </tr>
          </thead>

          <tbody>
            <% @trip_files.each do |tf| %>
              <tr>
                
                <td><%= "#{tf.flight} #{tf.flight_number}" %></td>
                <td><%= tf.created_at.strftime("%d %b %Y - %H:%M") %>
                <td><%= link_to 'Show', tf, class: 'btn btn-outline-primary btn-sm' %> 
                    <%#= link_to 'Download', tf.doc.url, download: '', class: 'btn btn-outline-success btn-sm' %> 
                    <%= link_to 'Edit', edit_trip_file_path(tf), class: 'btn btn-outline-warning btn-sm' %> 
                    <%= link_to 'Delete', tf, method: :delete, class: 'btn btn-outline-danger btn-sm' %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= link_to 'New Record', new_trip_file_path, class: 'btn btn-success' %>
        <%#= submit_tag "Download", class: 'awb-button btn2' %>
      </div>
    </div>
  </div>

app/views/trip_files/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-12">
			<br><br>
			<h1 class="red-heading">Export Manifest Trip File Uploader</h1>
			<p>Key in Flight Details, Snap a picture and Submit!</p>
		</div>
	</div>

	<div class="col-md-4 col-12">
		<%= render 'form', trip_file: @trip_file %>
	</div>
</div>

app/views/trip_files/show.html.erb
<div class="container my-4">

	<% if notice %>
	<div class="alert alert-success alert-dismissible fade show">
		<button type="button" class="close" data-dismiss="alert">&times;</button>
		<p id="notice"><%= notice %></p>
	</div>
	<% end %>

	<div class="jumbotron bg-light py-4">
		<div class="row">
			<figure class="figure">
				<%= image_tag @trip_file.doc.url, class: "figure-img img-fluid rounded", width: "40%" %>
				<figcaption class="figure-caption" style="font-size: 18px;">Flight : <%= "#{@trip_file.flight} #{@trip_file.flight_number}"  %></figcaption>
			</figure>
		</div>
		<div class="row">
			<%= link_to 'Create New', new_trip_file_path, class: 'awb-button btn btn-success' %>
		</div>
	</div>
</div>